# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6d66c75fa931573d81ac60164881d09e17bc84eb60bbc7c3bf7bd6a992643a8a0244f23a8650c1f4c7f53ced9e0b22eefb5c833509c5e6fa4663334dda8bb63

test:
  secret_key_base: 2371ace6c70cfb5d800ff59ca7e1d95fd678b7b97e5ec469436027484bd3e7339fba259c6f1c40c6b172d25b9b7e9f03e256e6708f75c4ff427da43b1c3817c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
