source 'https://rubygems.org'

ruby "2.1.4"

gem 'rails', '4.1.7'
gem 'bootstrap-sass', '~> 3.3.1'
gem 'sass-rails', '>= 3.2'
gem 'autoprefixer-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem "paperclip", "~> 4.2"
gem 'jbuilder', '~> 2.0'

group :production do
    gem 'pg'
    gem 'rails_12factor'
end

group :development, :test do
    gem 'sqlite3'
    gem 'spring'
end

group :doc do
    gem 'sdoc', '~> 0.4.0', require: false
end

